# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources (README.md file)
- Happy learning!

In [34]:
# import numpy and pandas
import pandas as pd
import numpy as np
import scipy.stats as st
from scipy.stats import trim_mean, mode, skew, gaussian_kde, pearsonr, spearmanr, beta
from statsmodels.stats.weightstats import ztest as ztest

from scipy.stats import ttest_ind, norm, t
from scipy.stats import f_oneway
from scipy.stats import sem

# Challenge 1

This is a placeholder to make the AI corrector be able to find the correct exercise for feedback

In [35]:
# Run this code:
salaries = pd.read_csv(r"C:\Users\javie\Desktop\Ironhack\Sexta semana\Lab18\lab-hypothesis-testing\data\Current_Employee_Names__Salaries__and_Position_Titles.csv")
salaries.head()

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
0,"AARON, JEFFERY M",SERGEANT,POLICE,F,Salary,NaN,101442.0,NaN
1,"AARON, KARINA",POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,F,Salary,NaN,94122.0,NaN
2,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,F,Salary,NaN,101592.0,NaN
3,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,F,Salary,NaN,110064.0,NaN
4,"ABASCAL, REECE E",TRAFFIC CONTROL AIDE-HOURLY,OEMC,P,Hourly,20.0,NaN,19.86

# Challenge 2 - Hypothesis Tests

In this section of the lab, we will test whether the hourly wage of all hourly workers is significantly different from $30/hr. Import the correct one sample test function from scipy and perform the hypothesis test for a 95% two sided confidence interval.

In [36]:
#H0: \mu = 30
#H1: \mu != 30

In [37]:
salaries["Hourly Rate"].isnull().sum()

np.int64(25161)

In [38]:
hourly_rate = salaries["Hourly Rate"].dropna()
hourly_rate.isnull().sum()

np.int64(0)

In [39]:
hourly_rate.shape

(8022,)

In [40]:
#One sample test function
st.ttest_1samp(hourly_rate, 30)

TtestResult(statistic=np.float64(20.6198057854942), pvalue=np.float64(4.3230240486229894e-92), df=np.int64(8021))

In [41]:
#CONCLUSION: There is sufficiente evidence (p-value < 0,05) to suggest that the Hourly rate is not = 30

In [42]:
#Sample mean
wage_mean = hourly_rate.mean()
wage_mean

np.float64(32.78855771628024)

In [43]:
#Sample standar dev
s = hourly_rate.std(ddof=1)
s

12.11257268427681

In [44]:
z_score = st.norm.ppf(1-((1-0.95)/2))
z_score

np.float64(1.959963984540054)

In [45]:
#Intervals
print("left end: ", wage_mean - z_score* (s/np.sqrt(8022)))
print("right end: ", wage_mean + z_score* (s/np.sqrt(8022)))

left end:  32.52349834813791
right end:  33.05361708442256

In [46]:
st.t.interval(0.95,8022-1, loc=wage_mean, scale=s/np.sqrt(8022))

(np.float64(32.52345834488425), np.float64(33.05365708767623))

In [47]:
# First we can say that there is evidence that the wage per hours is over $30/hour
# $30/hour is out of the interval

# Challenge 3

This is a placeholder to make the AI corrector be able to find the correct exercise for feedback

# Challenge 4 -  Hypothesis Tests of Proportions

## This challenge is OPTIONAL

Another type of one sample test is a hypothesis test of proportions. In this test, we examine whether the proportion of a group in our sample is significantly different than a fraction. 

You can read more about one sample proportion tests [here](http://sphweb.bumc.bu.edu/otlt/MPH-Modules/BS/SAS/SAS6-CategoricalData/SAS6-CategoricalData2.html).

In the cell below, use the `proportions_ztest` function from `statsmodels` to perform a hypothesis test that will determine whether the number of hourly workers in the City of Chicago is significantly different from 25% at the 95% confidence level.

In [53]:
from statsmodels import proportions_ztest

ImportError: cannot import name 'proportions_ztest' from 'statsmodels' (c:\Users\javie\anaconda3\Lib\site-packages\statsmodels\__init__.py)

In [48]:
# H0 = \mu = 0.25
# H1 = \mu != 0.25

In [49]:
salaries.head()

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
0,"AARON, JEFFERY M",SERGEANT,POLICE,F,Salary,NaN,101442.0,NaN
1,"AARON, KARINA",POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,F,Salary,NaN,94122.0,NaN
2,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,F,Salary,NaN,101592.0,NaN
3,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,F,Salary,NaN,110064.0,NaN
4,"ABASCAL, REECE E",TRAFFIC CONTROL AIDE-HOURLY,OEMC,P,Hourly,20.0,NaN,19.86

In [51]:
n = len(salaries)
hourly_workers = np.sum(salaries["Salary or Hourly"]== "Hourly")
hourly_workers, n

(np.int64(8022), 33183)

In [52]:
stat, pvalue = proportions_ztest(hourly_workers, n, value=0.25)

stat, pvalue

NameError: name 'proportions_ztest' is not defined